sudo: false
language: C
os:
  - linux
  - osx
compiler:
  - gcc
  - clang

install:
  - git clone --branch=dev https://github.com/xmake-io/xmake.git xmake-io/xmake --depth 1
  - cd ./xmake-io/xmake
  - ./scripts/get.sh __local__
  - cd -

script:
  - xmake repo --add xmake-repo-dev https://github.com/xmake-io/xmake-repo.git dev
  - xmake -y -v

